baseURL = '/'
languageCode = 'en-us'
title = 'Febrina Boer'
theme = 'hugo-creative-portfolio-theme'

[params]
style = 'default'
description = 'lorem ipsum'

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = "portfolio/"
home = true

[[params.navlinks]]
name = "About"
url = "about/"

[[params.navlinks]]
name = "Commission"
url = "commission/"

[[params.navlinks]]
name = "Blog"
url = "posts/"
